server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_user_db
    username: yourUsername
    password: yourPassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: ecommerce-user-service
